- name: check marathon container
  command: docker ps -a
  register: containers

- name: run marathon
  shell: docker run --net="host" --name=sys-marathon-container -d pytnru/sys-marathon --master zk://{{local_ip}}:2181/mesos --zk zk://{{local_ip}}:2181/marathon
  when: "{{ 'sys-marathon-container' not in containers.stdout }}"

- name: register in consul
  template: src=marathon_tmp.j2
            dest=/tmp/marathon.json
            mode=666

- name: curl
  shell:  curl -X PUT -d @/tmp/marathon.json http://localhost:8500/v1/agent/service/register